blog/urls.py
"""Urls for the demo of Zinnia"""
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls import patterns
from django.views.generic.base import RedirectView
from django.views.decorators.cache import cache_page
from django.contrib.auth.decorators import login_required

from zinnia.sitemaps import TagSitemap
from zinnia.sitemaps import EntrySitemap
from zinnia.sitemaps import CategorySitemap
from zinnia.sitemaps import AuthorSitemap
from filebrowser.sites import site

from flatblocks.views import edit
from .views import EntryDetail, EntryHotIndex, EntryFeaturedIndex

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^flatblocks/(?P<pk>\d+)/edit/$', login_required(edit), name='flatblocks-edit'),
    url(r'^flatpages/', include('django.contrib.flatpages.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'^xmlrpc/$', 'django_xmlrpc.views.handle_xmlrpc'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^article/(?P<slug>\d+)/$', cache_page(60 * 60 * 10)(EntryDetail.as_view()), name='zinnia_entry_detail'),
    url(r'^', include('zinnia.urls')),
)

sitemaps = {
    'tags': TagSitemap,
    'blog': EntrySitemap,
    'authors': AuthorSitemap,
    'categories': CategorySitemap
}

urlpatterns += patterns(
    'django.contrib.sitemaps.views',
    url(r'^sitemap.xml$', 'index',
        {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', 'sitemap',
        {'sitemaps': sitemaps}),
)

urlpatterns += patterns(
    '',
    url(r'^400/$', 'django.views.defaults.bad_request'),
    url(r'^403/$', 'django.views.defaults.permission_denied'),
    url(r'^404/$', 'django.views.defaults.page_not_found'),
    url(r'^500/$', 'django.views.defaults.server_error'),
)

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT})
    )

mysite/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # url(r'^admin/', include(admin.site.urls)),
)

zinnia/models/category.py
"""Category model for Zinnia"""
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible

from mptt.models import MPTTModel
from mptt.models import TreeForeignKey
from mptt.managers import TreeManager

from zinnia.managers import entries_published
from zinnia.managers import EntryRelatedPublishedManager


@python_2_unicode_compatible
class Category(MPTTModel):
    """
    Simple model for categorizing entries.
    """

    title = models.CharField(
        _('title'), max_length=255)

    slug = models.SlugField(
        _('slug'), unique=True, max_length=255,
        help_text=_("Used to build the category's URL."))

    description = models.TextField(
        _('description'), blank=True)

    parent = TreeForeignKey(
        'self',
        related_name='children',
        null=True, blank=True,
        verbose_name=_('parent category'))

    objects = TreeManager()
    published = EntryRelatedPublishedManager()

    def entries_published(self):
        """
        Returns category's published entries.
        """
        return entries_published(self.entries)

    @property
    def tree_path(self):
        """
        Returns category's tree path
        by concatening the slug of his ancestors.
        """
        if self.parent_id:
            return '/'.join(
                [ancestor.slug for ancestor in self.get_ancestors()] +
                [self.slug])
        return self.slug

    @models.permalink
    def get_absolute_url(self):
        """
        Builds and returns the category's URL
        based on his tree path.
        """
        return ('zinnia_category_detail', (self.tree_path,))

    def __str__(self):
        return self.title

    class Meta:
        """
        Category's meta informations.
        """
        app_label = 'zinnia'
        ordering = ['title']
        verbose_name = _('category')
        verbose_name_plural = _('categories')

    class MPTTMeta:
        """
        Category MPTT's meta informations.
        """
        order_insertion_by = ['title']

zinnia/models/entry.py
"""Entry model for Zinnia"""
from zinnia.settings import ENTRY_BASE_MODEL
from zinnia.models_bases import load_model_class


class Entry(load_model_class(ENTRY_BASE_MODEL)):
    """
    The final Entry model based on inheritence.
    """

blog/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.views.generic.dates import BaseArchiveIndexView
from django.views.generic.detail import DetailView

from zinnia.models.entry import Entry
from zinnia.views.archives import EntryArchiveMixin
from zinnia.views.mixins.entry_preview import EntryPreviewMixin
from zinnia.views.mixins.entry_protection import EntryProtectionMixin
from zinnia.views.mixins.templates import EntryQuerysetArchiveTodayTemplateResponseMixin

class EntryHotIndex(EntryArchiveMixin,
                 EntryQuerysetArchiveTodayTemplateResponseMixin,
                 BaseArchiveIndexView):
    """
    View returning the archive index.
    """
    template_name = 'zinnia/entry_list.html'
    context_object_name = 'entry_list'

class EntryFeaturedIndex(EntryArchiveMixin,
                 EntryQuerysetArchiveTodayTemplateResponseMixin,
                 BaseArchiveIndexView):
    """
    View returning the archive index.
    """
    template_name = 'zinnia/entry_list.html'
    context_object_name = 'entry_list'

class EntryDetail(EntryPreviewMixin,
                  EntryProtectionMixin,
                  DetailView):
    queryset = Entry.published.on_site()
    template_name_field = 'template'

zinnia/views/archives.py
"""Views for Zinnia archives"""
import datetime

from django.utils import timezone
from django.views.generic.dates import BaseArchiveIndexView
from django.views.generic.dates import BaseYearArchiveView
from django.views.generic.dates import BaseMonthArchiveView
from django.views.generic.dates import BaseWeekArchiveView
from django.views.generic.dates import BaseDayArchiveView
from django.views.generic.dates import BaseTodayArchiveView

from zinnia.models.entry import Entry
from zinnia.views.mixins.archives import ArchiveMixin
from zinnia.views.mixins.archives import PreviousNextPublishedMixin
from zinnia.views.mixins.callable_queryset import CallableQuerysetMixin
from zinnia.views.mixins.prefetch_related import PrefetchCategoriesAuthorsMixin
from zinnia.views.mixins.templates import \
    EntryQuerysetArchiveTemplateResponseMixin
from zinnia.views.mixins.templates import \
    EntryQuerysetArchiveTodayTemplateResponseMixin


class EntryArchiveMixin(ArchiveMixin,
                        PreviousNextPublishedMixin,
                        PrefetchCategoriesAuthorsMixin,
                        CallableQuerysetMixin,
                        EntryQuerysetArchiveTemplateResponseMixin):
    """
    Mixin combinating:

    - ArchiveMixin configuration centralizing conf for archive views.
    - PrefetchCategoriesAuthorsMixin to prefetch related objects.
    - PreviousNextPublishedMixin for returning published archives.
    - CallableQueryMixin to force the update of the queryset.
    - EntryQuerysetArchiveTemplateResponseMixin to provide a
      custom templates for archives.
    """
    # queryset = Entry.published.all
    queryset = None


class EntryIndex(EntryArchiveMixin,
                 EntryQuerysetArchiveTodayTemplateResponseMixin,
                 BaseArchiveIndexView):
    """
    View returning the archive index.
    """
    template_name = 'zinnia/entry_list.html'
    context_object_name = 'entry_list'


class EntryYear(EntryArchiveMixin, BaseYearArchiveView):
    """
    View returning the archives for a year.
    """
    template_name = 'zinnia/entry_list.html'
    make_object_list = True
    template_name_suffix = '_archive_year'


class EntryMonth(EntryArchiveMixin, BaseMonthArchiveView):
    """
    View returning the archives for a month.
    """
    template_name = 'zinnia/entry_list.html'
    template_name_suffix = '_archive_month'


class EntryWeek(EntryArchiveMixin, BaseWeekArchiveView):
    """
    View returning the archive for a week.
    """
    template_name = 'zinnia/entry_list.html'
    template_name_suffix = '_archive_week'

    def get_dated_items(self):
        """
        Override get_dated_items to add a useful 'week_end_day'
        variable in the extra context of the view.
        """
        self.date_list, self.object_list, extra_context = super(
            EntryWeek, self).get_dated_items()
        self.date_list = self.get_date_list(self.object_list, 'day')
        extra_context['week_end_day'] = extra_context[
            'week'] + datetime.timedelta(days=6)
        return self.date_list, self.object_list, extra_context


class EntryDay(EntryArchiveMixin, BaseDayArchiveView):
    """
    View returning the archive for a day.
    """
    template_name = 'zinnia/entry_list.html'
    template_name_suffix = '_archive_day'


class EntryToday(EntryArchiveMixin, BaseTodayArchiveView):
    """
    View returning the archive for the current day.
    """
    template_name = 'zinnia/entry_list.html'
    template_name_suffix = '_archive_today'

    def get_dated_items(self):
        """
        Return (date_list, items, extra_context) for this request.
        And defines self.year/month/day for
        EntryQuerysetArchiveTemplateResponseMixin.
        """
        today = timezone.now()
        if timezone.is_aware(today):
            today = timezone.localtime(today)
        self.year, self.month, self.day = today.date().isoformat().split('-')
        return self._get_dated_items(today)

zinnia/views/authors.py
"""Views for Zinnia authors"""
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.list import BaseListView

from zinnia.settings import PAGINATION
from zinnia.models.author import Author
from zinnia.views.mixins.templates import EntryQuerysetTemplateResponseMixin
from zinnia.views.mixins.prefetch_related import PrefetchCategoriesAuthorsMixin


class AuthorList(ListView):
    """
    View returning a list of all published authors.
    """

    def get_queryset(self):
        """
        Return a queryset of published authors,
        with a count of their entries published.
        """
        return Author.published.all().annotate(
            count_entries_published=Count('entries'))


class BaseAuthorDetail(object):
    """
    Mixin providing the behavior of the author detail view,
    by returning in the context the current author and a
    queryset containing the entries written by author.
    """

    def get_queryset(self):
        """
        Retrieve the author by his username and
        build a queryset of his published entries.
        """
        self.author = get_object_or_404(
            Author, **{Author.USERNAME_FIELD: self.kwargs['username']})
        return self.author.entries_published()

    def get_context_data(self, **kwargs):
        """
        Add the current author in context.
        """
        context = super(BaseAuthorDetail, self).get_context_data(**kwargs)
        context['author'] = self.author
        return context


class AuthorDetail(EntryQuerysetTemplateResponseMixin,
                   PrefetchCategoriesAuthorsMixin,
                   BaseAuthorDetail,
                   BaseListView):
    """
    Detailed view for an Author combinating these mixins:

    - EntryQuerysetTemplateResponseMixin to provide custom templates
      for the author display page.
    - PrefetchCategoriesAuthorsMixin to prefetch related Categories
      and Authors to belonging the entry list.
    - BaseAuthorDetail to provide the behavior of the view.
    - BaseListView to implement the ListView.
    """
    model_type = 'author'
    paginate_by = PAGINATION
    template_name = 'zinnia/entry_list.html'
    
    def get_model_name(self):
        """
        The model name is the author's username.
        """
        return self.author.get_username()

zinnia/views/capabilities.py
"""Views for Zinnia capabilities"""
from django.contrib.sites.models import Site
from django.views.generic.base import TemplateView

from zinnia.settings import PROTOCOL
from zinnia.settings import COPYRIGHT
from zinnia.settings import FEEDS_FORMAT


class CapabilityView(TemplateView):
    """
    Base view for the weblog capabilities.
    """

    def get_context_data(self, **kwargs):
        """
        Populate the context of the template
        with technical informations for building urls.
        """
        context = super(CapabilityView, self).get_context_data(**kwargs)
        context.update({'protocol': PROTOCOL,
                        'copyright': COPYRIGHT,
                        'feeds_format': FEEDS_FORMAT,
                        'site': Site.objects.get_current()})
        return context


class HumansTxt(CapabilityView):
    """
    http://humanstxt.org/
    """
    content_type = 'text/plain'
    template_name = 'zinnia/humans.txt'


class RsdXml(CapabilityView):
    """
    http://en.wikipedia.org/wiki/Really_Simple_Discovery
    """
    content_type = 'application/rsd+xml'
    template_name = 'zinnia/rsd.xml'


class WLWManifestXml(CapabilityView):
    """
    http://msdn.microsoft.com/en-us/library/bb463260.aspx
    """
    content_type = 'application/wlwmanifest+xml'
    template_name = 'zinnia/wlwmanifest.xml'


class OpenSearchXml(CapabilityView):
    """
    http://www.opensearch.org/
    """
    content_type = 'application/opensearchdescription+xml'
    template_name = 'zinnia/opensearch.xml'

zinnia/views/categories.py
"""Views for Zinnia categories"""
from django.shortcuts import get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.list import BaseListView

from zinnia.models.category import Category
from zinnia.models.entry import Entry
from zinnia.settings import PAGINATION
from zinnia.views.mixins.templates import EntryQuerysetTemplateResponseMixin
from zinnia.views.mixins.prefetch_related import PrefetchCategoriesAuthorsMixin


def get_category_or_404(path):
    """
    Retrieve a Category instance by a path.
    """
    path_bits = [p for p in path.split('/') if p]
    return get_object_or_404(Category, slug=path_bits[-1])


class CategoryList(ListView):
    """
    View returning a list of all the categories.
    """
    queryset = Category.objects.all()


class BaseCategoryDetail(object):
    """
    Mixin providing the behavior of the category detail view,
    by returning in the context the current category and a
    queryset containing the entries published under it.
    """

    def get_queryset(self):
        """
        Retrieve the category by his path and
        build a queryset of her published entries.
        """
        
        special = self.request.GET.get('special', None)
        self.category = get_category_or_404(self.kwargs['path'])
        
        categories = [item.pk for item in self.category.get_descendants(True)]
        entries = Entry.published.filter(categories__in=categories)
        
        if special == 'hot':
            return entries.filter(comment_count__gt=0)
        elif special == 'featured':
            return entries.filter(featured=True)
        else:
            return entries

    def get_context_data(self, **kwargs):
        """
        Add the current category in context.
        """
        context = super(BaseCategoryDetail, self).get_context_data(**kwargs)
        context['category'] = self.category
        context['special_flag'] = self.request.GET.get('special', '')
        
        return context


class CategoryDetail(EntryQuerysetTemplateResponseMixin,
                     PrefetchCategoriesAuthorsMixin,
                     BaseCategoryDetail,
                     BaseListView):
    """
    Detailed view for a Category combinating these mixins:

    - EntryQuerysetTemplateResponseMixin to provide custom templates
      for the category display page.
    - PrefetchCategoriesAuthorsMixin to prefetch related Categories
      and Authors to belonging the entry list.
    - BaseCategoryDetail to provide the behavior of the view.
    - BaseListView to implement the ListView.
    """
    model_type = 'category'
    paginate_by = PAGINATION
    template_name = 'zinnia/entry_list.html'
    
    def get_model_name(self):
        """
        The model name is the category's slug.
        """
        return self.category.slug

zinnia/views/random.py
"""Views for Zinnia random entry"""
from django.views.generic.base import RedirectView

from zinnia.models.entry import Entry


class EntryRandom(RedirectView):
    """
    View for handling a random entry
    simply do a redirection after the random selection.
    """
    permanent = False

    def get_redirect_url(self, **kwargs):
        """
        Get entry corresponding to 'pk' and
        return the get_absolute_url of the entry.
        """
        entry = Entry.published.all().order_by('?')[0]
        return entry.get_absolute_url()

blog/templates/zinnia/_entry_detail_base.html
{% load comments i18n zinnia_tags %}
<div id="entry-{{ object.pk }}" class="post">
    {% block entry-header %}
    <div class="entry-header">
        {% block entry-title %}
        <h1 id="post-title" class="entry-title"> {{ object.title|widont }}</h1>
        {% endblock entry-title %}
        
        {% block entry-info %}
        <p class="entry-cat">
            {% block entry-authors %}
            {% with authors=object.authors.all %}
            {% if authors|length %}
            {% trans "Written by" %}
            {% for author in authors %}
            <span class="vcard author">{{ author }}</span>{% if not forloop.last %}, {% endif %}
            {% endfor %}
            {% trans "on" context "on date" %}
            {% else %}
            {% trans "Written on" %}
            {% endif %}
            {% endwith %}
            {% endblock entry-authors %}
            {% block entry-published %}
            <abbr class="published" title="{{ object.creation_date|date:"c" }}">{{ object.creation_date|date:"DATE_FORMAT" }}</abbr>
            {% endblock entry-published %}
            {% block entry-categories %}
            {% with categories=object.categories.all %}
            {% if categories|length %}
            {% trans "in" %}
            {% for category in categories %}
            <a href="{{ category.get_absolute_url }}"
               title="{% blocktrans %}Show all entries in {{ category }}{% endblocktrans %}"
               rel="tag category">{{ category }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}{% endif %}.
            {% endwith %}
            {% endblock entry-categories %}
            共{{ object.access }}人围观
        </p>
        {% endblock entry-info %}
    </div>
    {% endblock entry-header %}

    {% block entry-body %}
    <div class="entry-body">
        {% block entry-image %}
        {% if object.image %}
        <div class="entry-banner" style="width: {{object.image.width}}px; height: {{object.image.height}}px;">
            <img src="{{ object.image.url }}" width={{object.image.width}} height={{object.image.height}} alt="{{ object.title }}"/>
        </div>
        {% endif %}
        {% endblock entry-image %}
        
        {% block entry-content %}
        <div class="entry-content">
            {{ object_content|safe }}
        </div>
        {% endblock entry-content %}
    </div>
    {% endblock entry-body %}

    <div class="entry-meta clear">
        <ul class="entry-relate-links">
            {% block entry-previous-entry %}
            {% with previous_entry=object.previous_entry %}
            {% if previous_entry %}
            <li>
                <span>上一篇 >：</span>
                <a href="{{ previous_entry.get_absolute_url }}" title="{{ previous_entry.title }}" rel="prev">{{ previous_entry.title }}</a>
            </li>
            {% endif %}
            {% endwith %}
            {% endblock entry-previous-entry %}
                
            {% block entry-next-entry %}
            {% with next_entry=object.next_entry %}
            {% if next_entry %}
            <li>
                <span>下一篇 >：</span>
                <a href="{{ next_entry.get_absolute_url }}" title="{{ next_entry.title }}" rel="next"> {{ next_entry.title }} </a>
                {% endif %}
                {% endwith %}
                {% endblock entry-next-entry %}
            </li>
        </ul>
        
        {% block entry-similar-entries %}
        <h3>{% trans "Similar entries" %}</h3>
        {% get_similar_entries 8 %}
        {% endblock entry-similar-entries %}
    </div>

</div>

blog/templates/zinnia/author_list.html
{% extends "zinnia:zinnia/author_list.html" %}
{% load i18n %}

{% block content %}
<h2>{% trans "Author list" %}</h2>

<ul class="list-group">
  {% for object in object_list %}
  <li class="vcard list-group-item">
    <a href="{{ object.get_absolute_url }}"
       title="{% blocktrans with author=object %}Show all {{ author }}'s entries{% endblocktrans %}"
       class="fn url{% if not author.get_full_name %} nickname{% endif %}">{{ object }}</a>
    <span class="badge">
      {% blocktrans count entry_count=object.count_entries_published %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
    </span>
  </li>
  {% empty %}
  <li>
    {% trans "No authors yet." %}
  </li>
  {% endfor %}
</ul>
{% endblock content %}

blog/templates/zinnia/base.html
{% extends "zinnia:zinnia/base.html" %}
{% load zinnia_tags i18n %}

{% block sidebar %}
{% if user.is_authenticated %}
<div id="widget-tools" class="widget panel panel-danger">
    <div class="widget_t"></div>
    <div class="widget_c">
        <div class="item_title">{% trans "Tools" %}</div>
        <ul class="randomposts">
            {% if perms.zinnia %}
            <li class="list-group-item">
              <a href="{% url 'admin:app_list' 'zinnia' %}" title="{% trans "Dashboard" %}">
                <span class="glyphicon glyphicon-book"></span>
                {% trans "Dashboard" %}
              </a>
            </li>
            {% endif %}
            
            {% if perms.zinnia.add_entry %}
            <li class="list-group-item">
              <a href="{% url 'admin:zinnia_entry_add' %}" title="{% trans "Post an entry" %}">
                <span class="glyphicon glyphicon-pencil"></span>
                {% trans "Post an entry" %}
              </a>
            </li>
            {% endif %}
            
            {% block admin-tools %}
            {% endblock admin-tools %}
            
            <li class="list-group-item">
              <a href="{% url 'admin:logout' %}" title="{% trans "Log out" %}">
                <span class="glyphicon glyphicon-off"></span>
                {% trans "Log out" %}
              </a>
            </li>
        </ul>
    </div>
    <div class="widget_b"></div>
</div>
{% endif %}

{% block sidebar_categories %}
{% endblock %}

{% block sidebar_welcome %}
<div id="widget-welcome" class="widget panel panel-default">
    <div class="widget_t"></div>
    <div class="widget_c">
        <div class="item_title">欢迎访问欧泊影视</div>
        <div class="widget_content">
            <p>本博客分享一些电影资讯</p>
            <p>方便大家决定哪里电影值得观看提供更多的参考!</p>
            <p>最后致力于打造一个最佳的分享平台!</p>
        </div>
    </div>
    <div class="widget_b"></div>
</div>
{% endblock %}

<div id="widget-comments" class="widget panel panel-default">
    <div class="widget_t"></div>
    <div class="widget_c">
        <div class="item_title">{% trans "Recent comments" %}</div>
        {% get_recent_comments 10 %}
    </div>
    <div class="widget_b"></div>
</div>

<div id="widget-randoms" class="widget panel panel-default">
    <div class="widget_t"></div>
    <div class="widget_c">
        <div class="item_title">{% trans "Random entries" %}</div>
        {% get_random_entries 25 %}
    </div>
    <div class="widget_b"></div>
</div>
{% endblock sidebar %}

blog/templates/zinnia/category_list.html
{% extends "zinnia:zinnia/category_list.html" %}
{% load i18n mptt_tags %}

{% block content %}
<h2>{% trans "Category list" %}</h2>

<ul class="category-root list-group">
  {% recursetree object_list %}
  <li class="list-group-item">
    <a href="{{ node.get_absolute_url }}" title="{% blocktrans with category=node %}Show all entries in {{ category }}{% endblocktrans %}">{{ node }}</a>
    <span class="badge">
      {% blocktrans count entry_count=node.entries_published.count %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
    </span>
    {% if node.description %}<p>{{ node.description|striptags|safe }}</p>{% endif %}
    {% if not node.is_leaf_node %}
    <ul class="category-children category-{{ node.slug }}">
      {{ children }}
    </ul>
    {% endif %}
  </li>
  {% endrecursetree %}
  {% if not object_list %}
  <li class="list-group-item">
    {% trans "No categories yet." %}
  </li>
  {% endif %}
</ul>
{% endblock content %}

blog/templates/zinnia/entry_category_list.html
{% extends "zinnia/entry_list.html" %}
{% load i18n zinnia_tags %}

{% block sidebar_categories %}
{% get_categories %}
{% endblock %}

blog/templates/zinnia/entry_list.html
{% extends "zinnia/base.html" %}
{% load i18n zinnia_tags custom_tags %}

{% block meta-description %}{% trans "Latest entries for" %} {% if category %}{% trans "the category" %} {{ category }}{% if category.description %}: {{ category.description|striptags|safe }}{% endif %}{% endif %}{% if tag %}{% trans "the tag" %} {{ tag }}{% endif %}{% if author %}{% trans "the author" %} {{ author }}{% endif %}{% endblock meta-description %}

{% block meta-description-page %}{% if page_obj %}{% ifnotequal page_obj.number 1 %} {% trans "page" %} {{ page_obj.number }}{% endifnotequal %}{% endif %}{% endblock meta-description-page %}

{% block title %}{% if category %}{% trans "Category" %} {{ category }}{% endif %}{% if tag %}{% trans "Tag" %} {{ tag }}{% endif %}{% if author %}{% trans "Author" %} {{ author }}{% endif %}{% endblock title %}

{% block title-page %}{% if page_obj %}{% ifnotequal page_obj.number 1 %} - {% trans "Page" %} {{ page_obj.number }}{% endifnotequal %}{% endif %}{% endblock title-page %}

{% block body-class %}entry-list{% if page_obj %} paginated page-{{ page_obj.number }}{% endif %}{% if category %} category category-{{ category.slug }}{% endif %}{% if tag %} tag tag-{{ tag|slugify }}{% endif %}{% if author %} author author-{{ author|slugify }}{% endif %}{% endblock body-class %}

{% block hot%}
    {% if category  or tag or author%}
    <h1 style="display: none;">{% blocktrans %}Category archives: {{ category }}{% endblocktrans %}</h1>
    {%else%}
    {% ifequal page_obj.number 1 %}
    <div id="section_hot">
        <div id="hot_left" class="float-left">
            <div id="play_top" class="rbox_t"></div>
            <div id="play_center" class="rbox_c">{% hot_player %}</div>
            <div id="play_bottom" class="rbox_b"></div>
        </div>
        
        <div id="hot_right" class="float-left">
            <div id="hot_top" class="rbox_t"></div>
            <div id="hot_center" class="rbox_c">{% hot_tab %}</div>
            <div id="hot_bottom" class="rbox_b">
            </div>
        </div>
    </div>
    {% endifequal %}
    {% endif %}
{%endblock%}

{% block content %}
<div id="postlist">
    <div class="blue_bar">
        <ul id="all_news_nav">
            <li><a {%if special_flag == '' %}class="current"{% endif %} href="{{ request.path }}">全部文章</a></li>
            <li>|</li>
            <li><a {%if special_flag == 'featured' %}class="current"{% endif %} href="?special=featured">精华文章</a></li>
            <li>|</li>
            <li><a {%if special_flag == 'hot' %}class="current"{% endif %} href="?special=hot">人气推荐</a></li>
        </ul>
    </div>
    <div class="article-abstract">
    {% block content-loop %}
    {% for object in object_list %}
        {% include 'zinnia/abstract.html'%}
    {% empty %}
        <p class="info">
            <a href="{% url 'admin:zinnia_entry_add' %}">{% trans "No entries yet." %}</a>
        </p>
    {% endfor %}
    {% endblock content-loop %}
    
    {% block content-pagination %}
    {% if is_paginated %}
        {% zinnia_pagination page_obj %}
    {% endif %}
    {% endblock content-pagination %}
    
    {% block content-related %}
    {% endblock content-related %}
    </div>
</div>
{% endblock content %}

{% block sidebar_categories %}
{% get_categories %}
{% endblock %}

{% block admin-tools %}
    {% if category and perms.zinnia.change_category %}
    <li>
        <a href="{% url 'admin:zinnia_category_change' category.pk %}" title="{% trans "Edit the category" %}">
            {% trans "Edit the category" %}
        </a>
    </li>
    {% endif %}
    {% if tag and perms.tagging.change_tag %}
    <li>
        <a href="{% url 'admin:tagging_tag_change' tag.pk %}" title="{% trans "Edit the tag" %}">
            {% trans "Edit the tag" %}
        </a>
    </li>
    {% endif %}
    {% if author and perms.auth.change_user %}
    <li>
        <a href="{% url 'change'|user_admin_urlname author.pk %}" title="{% trans "Edit the author" %}">
            {% trans "Edit the author" %}
        </a>
    </li>
    {% endif %}
{% endblock admin-tools %}